In [1]:
import torch 
x = torch.arange(4.0)
x

tensor([0., 1., 2., 3.])

In [2]:
#存储梯度
x.requires_grad_(True)
x.grad

In [4]:
y = 2 * torch.dot(x,x)
y

tensor(28., grad_fn=<MulBackward0>)

In [6]:
y.backward()
x.grad

RuntimeError: Trying to backward through the graph a second time (or directly access saved variables after they have already been freed). Saved intermediate values of the graph are freed when you call .backward() or autograd.grad(). Specify retain_graph=True if you need to backward through the graph a second time or if you need to access saved variables after calling backward.

In [7]:
x.grad == 4 * x

tensor([True, True, True, True])

In [17]:
x.grad.zero_()
y = x.sum()
y.backward()
x.grad

tensor([1., 1., 1., 1.])

In [19]:
x.grad.zero_()
y = x * x
y.sum().backward()
x.grad

tensor([0., 2., 4., 6.])

In [20]:
x.grad.zero_()
y = x * x
u = y.detach()
z = u * x 
 
z.sum().backward()
x.grad == u

tensor([True, True, True, True])

In [22]:
x.grad.zero_()
y.sum().backward()
x.grad == 2 * x

tensor([True, True, True, True])

In [34]:
def f(a):
    b = a * 2
    while b.norm() < 1000:
        b = b * 2
    if b.sum() > 0:
        c = b
    else: 
        c = 100 * b
    return c

a = torch.randn(size=(),requires_grad=True)
d = f(a)
d.backward()
d,a.grad == d/a

(tensor(1077.4165, grad_fn=<MulBackward0>), tensor(True))